### ISSUE TITLE
Playback of DRM protected streams fails

### ISSUE THREAD

**Issue by hardebusch** [flubshi/plugin.video.waipu.tv#1]
Channels of Öffentlich-rechtlicher Rundfunk (Das Erste, ZDF etc.) work just fine, but playback of DRM protected channels (like RTL) fails. I first noticed it today, a few days ago everything worked with the same configuration.

[kodi.log](https://github.com/flubshi/plugin.video.waipu.tv/files/3504995/kodi.log)

**Comment by hardebusch** [comment]
Issue seems fixed (there was an update for Widevine earlier today, maybe related?)

**Comment by flubshi** [comment]
Thanks for reporting the issue. I am currently on vacation and answers are delayed...
I am not sure if it is related to the widevine update. The waipu PVR plugin was also affected (see kodinerds forum). I will take a look at this the next days. Feel free to reopen this issue when it is broken again the next days.

**Comment by flubshi** [comment]
I read about it. I think you @tihadot are right - it was caused by an outdated widevine version: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/59
Thanks for your hint!
